nopspptsimulasi = {
    provinsiID: null,
    namaPropinsi: null,
	kotaID: null,
    namaKota: null,
	kecamatanID: null,
    namaKecamatan: null,
	kelurahanID: null,
    namaKelurahan: null,
	blokID: null,
	noUrut: null,
	noUrutExt: null,
	jenisOpId: null,
    tahunPajak: null,
	bukuJatuhTempo: [],
	bukuTerbit: [],
}