verifikasi = {
    noUrutItem: null,
    id: null,
    sptpd_Id: null,
    ppat_Id: null,
    wajibPajak_NIK: null,
    permohonanProvinsiID: null,
    permohonanKotaID: null,
    permohonanKecamatanID: null,
    permohonanKelurahanID: null,
    permohonanBlokID: null,
    noUrutPemohon: null,
    pemohonJenisOPID: null,
    opAlamat: null,
    opProvinsi: null,
    opKota: null,
    opKecamatan: null,
    opKelurahan: null,
    op_RtRW: null,
    opLuasTanah: null,
    opLuasBangunan: null,
    opLuasTanahBersama: null,
    opLuasBangunanBersama: null,
    njopLuasTanah: null,
    njopLuasBangunan: null,
    njopTanahBersama: null,
    njopBangunanBersama: null,
    nilaiOp: null,
    jenisPerolehanOp: null,
    noSertifikatOp: null,
    njopPbbOp: null,
    lokasiOp: null,
    tahunPajakSppt: null,
    npop: null,
    npoptkp: null,
    jenisSetoran: null,
    jenisSetoranNomor: null,
    jenisSetoranTanggal: null,
    jenisSetoranHitungSendiri: null,
    jenisSetoranCustom: null,
    jumlahSetor: null,
    nominalSPT: null,
    tanggal: null,
    noDokumen: null,
    nopPbbBaru: null,
    user_id: null,
    id_pp: null,
    jenisSetoranKeterangan: null,
    nilaiPasar: null,
    jenisPerolehan_id: null,
    inpAphb1: null,
    inpAphb2: null,
    inpAphb3: null,
    kodeValidasi: null,
    GambarOp: null,
    isLunas: null,
    validasiDisependa: null,
    validasiBank: null,
    tglValidasiDispenda: null,
    tglValidasiBank: null,
    pegawai_User_id: null,
    alasanReject: null,
    bank_Id: null,
    gambarInt: null,
    flagDispenda: null,
    flagPPAT: null,
    tanahInpAphb1: null,
    tanahInpAphb2: null,
    tanahInpAphb3: null,
    bangunanInpAphb1: null,
    bangunanInpAphb2: null,
    bangunanInpAphb3: null,
    tanahBersamaInpAphb1: null,
    tanahBersamaInpAphb2: null,
    tanahBersamaInpAphb3: null,
    bangunanBersamaInpAphb1: null,
    bangunanBersamaInpAphb2: null,
    bangunanBersamaInpAphb3: null,
    isKurangBayar: null,
    kurangBayar: null,
    sspdLama: null,
    noReff: null,
    idBilling: null,
    proses: null,
    namaWp: null,
    alamat: null,    
    provinsi_Id: null,
    provinsi_wp: null,
    kabupaten_id: null,
    kabupaten_wp: null,
    kecamatan_Id: null,
    kecamatan_wp: null,
    kelurahan_Id: null,
    kelurahan_wp: null,
    kodePos: null,
    rtRw: null,
    wajibPajak_id: null,
    approvePPAT: null,
    noPelayanan: null,
    namaPetugasLapangan: null,
    namaStaff: null,
    noAkta: null,
    tglAkta: null,
    pihakMengalihkan: null,
    tgl: null,
    rp: null,
    batas: null,
    pengurangan: null,
    skPengurangan: null,
    tglSkPengurangan: null,
    wajibPajak: null,
    tglExpBilling: null,
    jenisTransaksiSpop: null,
    pekerjaan: null,
    jenisTanah: null,
    jumlahBangunan: null,
    blokKavNo: null,
    rT: null,
    rw: null,   
    status:null, 
    pilihAlamat:null,
    hargaReferensi:null,
    lampiran: {
        a : null,
        b : null,
        c : null,
        d : null,
        e : null,
        f : null,
        g : null,
        h : null,
        i : null,
        j : null,
        k : null,
        l : null,
        buktiBayar : null,
        namaPetugas : null,
        namaKuasa : null,
        alamatKuasa : null,
    }
}
