permohonan = {
    id: null,
    kanwilId: null,
    kppbbId: null,
    noPelayanan:null,
    statusKolektif: null,
    noSuratPermohonan: null,
    jenisPelayanan: null,
    tanggalTerima: null,
    tanggalSelesai: null,
    tanggalPermohonan: null,
    nop: null,
    namaWP: null,
    letakOP: null,
    keterangan: null,
    tahunPajak: null,
    penerimaanBerkasTemp: [],
    penerimaanBerkas: null,
    catatan: null,
    userId: null,
    jenisPengurangan: null,
    persentasePengurangan: null,
    nip: null,
    penyerahan: {
        catatanPenyerahan: null,
        namaPenerima: null,
        statusSelesai: null,
        seksiBerkas: null,
        nipPenyerah: null,
        tanggalPenyerahan: null,
    },
}
