
verifikasiPermohonan = {
    id: null,
    kanwilId: null,
    kppbbId: null,
    noPelayanan:null,
    statusKolektif: null,
    noSuratPermohonan: null,
    jenisPelayanan: null,
    tanggalTerima: null,
    tanggalSelesai: null,
    tanggalPermohonan: null,
    nop: null,
    namaWP: null,
    letakOP: null,
    keterangan: null,
    tahunPajak: null,
    penerimaanBerkasTemp: [],
    penerimaanBerkas: null,
    catatan: null,
    userId: null,
    alasanPengurangan: null,
    jenisPengurangan: null,
    persentasePengurangan: null,
    nip: null,
    penyerahan: {
        catatanPenyerahan: null,
        namaPenerima: null,
        statusSelesai: null,
        seksiBerkas: null,
        nipPenyerah: null,
        tanggalPenyerahan: null,
    },
    oppbb: {
        kelurahan_kode: null,
        
        pstPermohonan_id: null,
        regWajibPajakPbb_id: null,
        noFormulirSpop: null,
        noPersil: null,
        jalan: null,
        blokKavNo: null,
        rw: null,
        rt: null,
        statusCabang: null,
        statusWp: null,
        totalLuasBumi: null,
        totalLuasBangunan: null,
        statusPeta: null,
        jenisTransaksi: null,
        tanggalPendataan: null,
        pendata_pegawai_nip: null,
        tanggalPemeriksaan: null,
        pemeriksa_pegawai_nip: null,
        tanggalPerekaman: null,
        perekam_pegawai_nip: null,
    
        regWajibPajakPbb: {
            nik: null,
            nama: null,
            jalan: null,
            blokKavNo: null,
            rw: null,
            rt: null,
            kelurahan_kode: null,
            daerah_kode: null,
            kodePos: null,
            telp: null,
            npwp: null,
            pekerjaan: null,
        },
        regObjekPajakBumi: {
            noBumi: null,
            kodeZnt: null,
            luasBumi: null,
            jenisBumi: null,
            nilaiSistemBumi: null,
    
            regObjekPajakBng : [],
        },
        regAnggotaObjekPajak: null,
        regIndukObjekPajak: null,
        regKunjunganKembali: null,
    
        nop: null,
        nopBersama: null,
        nopAsal: null
    }
}

regObjekPajakBngs = {
    pstPermohonan_id: null,
    noBangunan: null,
    jpb_kode: null,
    noFormulirSpop: null,
    tahunDibangun: null,
    tahunRenovasi: null,
    luasBangunan: null,
    kondisi: null,
    jenisKonstruksi: null,
    jenisAtap: null,
    kodeDinding: null,
    kodeLantai: null,
    kodeLangitLangit: null,
    nilaiSistem: null,
    jenisTransaksi: null,
    tanggalPendataan: null,
    pendata_pegawai_nip: null,
    tanggalPemeriksaan: null,
    pemeriksa_pegawai_nip: null,
    tanggalPerekaman: null,
    perekam_pegawai_nip: null,
    nop: null,
    jmlLantaiBng: null,
    fasilitasBangunan: null,

    regFasBangunan: {
        fbJumlahACSplit: null,
        fbJumlahACWindow: null,
        fbJumlahAC: null,
        fbLuasKolamRenang: null,
        fbTipeLapisanKolam: null,
        fbHalamanBerat: null,
        fbHalamanSendang: null,
        fbHalamanRingan: null,
        fbHalamanLantai: null,
        fbTenisLampuBeton: null,
        fbTenisTanpaLampuBeton: null,
        fbTenisAspal1: null,
        fbTenisAspal2: null,
        fbTenisLiatRumput1: null,
        fbTenisLiatRumput2: null,
        fbLiftPenumpang: null,
        fbLiftKapsul: null,
        fbLiftBarang: null,
        fbTangga80: null,
        fbTangga81: null,
        fbPagarPanjang: null,
        fbPagarBahan: null,
        fbPKHydrant: null,
        fbPKSplinkler: null,
        fbPKFireAI: null,
        fbPABX: null,
        fbSumur: null,

        jpbKlinikACCentralKamar: null,
        jpbKlinikACCentralRuang: null,
        jpbHotelJenis: null,
        jpbHotelBintang: null,
        jpbHotelJmlKamar: null,
        jpbHotelACCentralKamar: null,
        jpbHotelACCentralRuang: null,
        jpbApartemenJumlah: null,
        jpbApartemenACCentralKamar: null,
        jpbApartemenACCentralLain: null,
        jpbTankiKapasitas: null,
        jpbTankiLetak: null,
        jpbProdTinggi: null,
        jpbProdLebar: null,
        jpbProdDaya: null,
        jpbProdKeliling: null,
        jpbProdLuas: null,

        kelasBangunan: null,
    }
}

responseVerifikasi = {
    id: null,
    noPelayanan: null,
    nop: null,
    kanwilId: null,
    kppbbId: null,
    tahunPelayanan: null,
    bundlePelayanan: null,
    noUrutPelayanan: null,
    noSuratPermohonan: null,
    tanggalSuratPermohonan: null,
    namaWP: null,
    letakOP: null,
    keterangan: null,
    catatan: null,
    statusKolektif: null,
    tanggalTerima: null,
    nip: null,
    penerimaanBerkas: null,
    pstBaru: {
        id: null,
        permohonanId: null,
        kanwilId: null,
        kppbbId: null,
        tahunPelayanan: null,
        jenisPelayanan: null,
        noUrutPelayanan: null,
        namaWP: null,
        letakOP: null,
        createdAt: null,
        updatedAt: null,
        deletedAt: null
    },
    pstDetil: [],
    pstPengurangan: null,
    pstLampiran: {
        id: null,
        buktiKepemilikan: null,
        permohonanId: null,
        tahunPelayanan: null,
        bundlePelayanan: null,
        noUrutPelayanan: null,
        lampiranPermohonan: null,
        lampiranSuratKuasa: null,
        lampiranSK: null,
        lampiranKTP: null,
        lampiranKK: null,
        lampiranSertifikatTanah: null,
        lampiranSppt: null,
        lampiranImb: null,
        lampiranAkte: null,
        lampiranSkPensiun: null,
        lampiranSpptStts: null,
        lampiranSTTS: null,
        lampiranSkPengurangan: null,
        lampiranSkKeberatan: null,
        lampiranSkkpPbb: null,
        lampiranSpmkpPbb: null,
        lampiranLainLain: null,
        lampiranLaporanKeuangan: null,
        lampiranLikuid: null,
        lampiranLhp: null,
        lampiranSlipGaji: null,
        lampiranListrik: null,
        lampiranLetakOP: null,
        lampiranTelaah: null,
        lampiranHakMilik: null,
        lampiranFotoOP: null,
        provinsiKode: null,
        daerahKode: null,
        kecamatanKode: null,
        kelurahanKode: null,
        blokKode: null,
        noUrutKode: null,
        jenisOP: null,
        createdAt: null,
        updatedAt: null,
        deletedAt: null
    },
    pstOpjekPajakPBB: {
        id: null,
        pstPermohonan_id: null,
        regWajibPajakPbb_id: null,
        noFormulirSpop: null,
        noPersil: null,
        jalan: null,
        blokKavNo: null,
        rw: null,
        rt: null,
        statusCabang: null,
        statusWp: null,
        totalLuasBumi: null,
        totalLuasBangunan: null,
        njopBumi: null,
        njopBangunan: null,
        statusPeta: null,
        status: null,
        nopAsal: null,
        jenisTransaksi: null,
        tanggalPendataan: null,
        pendata_pegawai_nip: null,
        tanggalPemeriksaan: null,
        pemeriksa_pegawai_nip: null,
        tanggalPerekaman: null,
        perekam_pegawai_nip: null,
        updatedAt: null,
        deletedAt: null
    },
    pstWajibPajakPBB: {
        id: null,
        nik: null,
        nama: null,
        jalan: null,
        blokKavNo: null,
        rw: null,
        rt: null,
        kelurahan_kode: null,
        daerah_kode: null,
        kodePos: null,
        telp: null,
        npwp: null,
        pekerjaan: null,
        user_ID: null,
        createdAt: null,
        updatedAt: null,
        deletedAt: null
    },
    pstOPBumi: {
        id: null,
        pstPermohonan_id: null,
        noBumi: null,
        kodeZnt: null,
        luasBumi: null,
        jenisBumi: null,
        nilaiSistemBumi: null,
        createdAt: null,
        updatedAt: null,
        deletedAt: null
    },
    pstLogApprovalRes:{
        user_staff:null,
        user_kasubid:null,
        user_kabid:null,
        user_sekban:null,
        user_kaban:null,
        tgl_staff:null,
        tgl_kasubid:null,
        tgl_kabid:null,
        tgl_sekban:null,
        tgl_kaban:null,
        catatan: null,
    },
    pstOPBangunan: [],
    pstFasilitasBangunan: [],
    pstJpb: null
}

pstLaporan = {
    permohonan_id: null,
	user_id: null,
	catatan: null,
	keterangan: null,
	status: null,
	jabatan: null,
	divisi: null,
}