
verifikasiPermohonan = {
    id: null,
    kanwilId: null,
    kppbbId: null,
    noPelayanan:null,
    statusKolektif: null,
    noSuratPermohonan: null,
    jenisPelayanan: null,
    tanggalTerima: null,
    tanggalSelesai: null,
    tanggalPermohonan: null,
    nop: null,
    namaWP: null,
    letakOP: null,
    keterangan: null,
    tahunPajak: null,
    penerimaanBerkasTemp: [],
    penerimaanBerkas: null,
    catatan: null,
    userId: null,
    alasanPengurangan: null,
    jenisPengurangan: null,
    persentasePengurangan: null,
    nip: null,
    penyerahan: {
        catatanPenyerahan: null,
        namaPenerima: null,
        statusSelesai: null,
        seksiBerkas: null,
        nipPenyerah: null,
        tanggalPenyerahan: null,
    },
    oppbb: {
        kelurahan_kode: null,
        
        pstPermohonan_id: null,
        regWajibPajakPbb_id: null,
        noFormulirSpop: null,
        noPersil: null,
        jalan: null,
        blokKavNo: null,
        rw: null,
        rt: null,
        statusCabang: null,
        statusWp: null,
        totalLuasBumi: null,
        totalLuasBangunan: null,
        statusPeta: null,
        jenisTransaksi: null,
        tanggalPendataan: null,
        pendata_pegawai_nip: null,
        tanggalPemeriksaan: null,
        pemeriksa_pegawai_nip: null,
        tanggalPerekaman: null,
        perekam_pegawai_nip: null,
    
        regWajibPajakPbb: {
            nik: null,
            nama: null,
            jalan: null,
            blokKavNo: null,
            rw: null,
            rt: null,
            kelurahan_kode: null,
            daerah_kode: null,
            kodePos: null,
            telp: null,
            npwp: null,
            pekerjaan: null,
        },
        regObjekPajakBumi: {
            noBumi: null,
            kodeZnt: null,
            luasBumi: null,
            jenisBumi: null,
            nilaiSistemBumi: null,
    
            regObjekPajakBng : [],
        },
        regAnggotaObjekPajak: null,
        regIndukObjekPajak: null,
        regKunjunganKembali: null,
    
        nop: null,
        nopBersama: null,
        nopAsal: null
    }
}

regObjekPajakBngs = {
    pstPermohonan_id: null,
    noBangunan: null,
    jpb_kode: null,
    noFormulirSpop: null,
    tahunDibangun: null,
    tahunRenovasi: null,
    luasBangunan: null,
    kondisi: null,
    jenisKonstruksi: null,
    jenisAtap: null,
    kodeDinding: null,
    kodeLantai: null,
    kodeLangitLangit: null,
    nilaiSistem: null,
    jenisTransaksi: null,
    tanggalPendataan: null,
    pendata_pegawai_nip: null,
    tanggalPemeriksaan: null,
    pemeriksa_pegawai_nip: null,
    tanggalPerekaman: null,
    perekam_pegawai_nip: null,
    nop: null,
    jmlLantaiBng: null,
    fasilitasBangunan: null,

    regFasBangunan: {
        fbJumlahACSplit: null,
        fbJumlahACWindow: null,
        fbJumlahAC: null,
        fbLuasKolamRenang: null,
        fbTipeLapisanKolam: null,
        fbHalamanBerat: null,
        fbHalamanSendang: null,
        fbHalamanRingan: null,
        fbHalamanLantai: null,
        fbTenisLampuBeton: null,
        fbTenisTanpaLampuBeton: null,
        fbTenisAspal1: null,
        fbTenisAspal2: null,
        fbTenisLiatRumput1: null,
        fbTenisLiatRumput2: null,
        fbLiftPenumpang: null,
        fbLiftKapsul: null,
        fbLiftBarang: null,
        fbTangga80: null,
        fbTangga81: null,
        fbPagarPanjang: null,
        fbPagarBahan: null,
        fbPKHydrant: null,
        fbPKSplinkler: null,
        fbPKFireAI: null,
        fbPABX: null,
        fbSumur: null,

        jpbKlinikACCentralKamar: null,
        jpbKlinikACCentralRuang: null,
        jpbHotelJenis: null,
        jpbHotelBintang: null,
        jpbHotelJmlKamar: null,
        jpbHotelACCentralKamar: null,
        jpbHotelACCentralRuang: null,
        jpbApartemenJumlah: null,
        jpbApartemenACCentralKamar: null,
        jpbApartemenACCentralLain: null,
        jpbTankiKapasitas: null,
        jpbTankiLetak: null,
        jpbProdTinggi: null,
        jpbProdLebar: null,
        jpbProdDaya: null,
        jpbProdKeliling: null,
        jpbProdLuas: null,

        kelasBangunan: null,
    }
}

