penetapan_massal = {
  tahunPajak: null,
  provinsiID: null,
  namaPropinsi: null,
  kotaID: null,
  namaKota: null,
  kecamatanID: null,
  namaKecamatan: null,
  kelurahanID: null,
  namaKelurahan: null,
  jmlRecord: null,
  recordKe: null,
  noUrut: null,
  isLoading: false,
  tglJatuhTempo1: null,
  tglJatuhTempo2: null,
  tglJatuhTempo3: null,
  tglJatuhTempo4: null,
  tglJatuhTempo5: null,
  tglTerbit1: null,
  tglTerbit2: null,
  tglTerbit3: null,
  tglTerbit4: null,
  tglTerbit5: null,
  bukuIds: [],
  formType: 'form',
}