potensiop = {
	jenisPajak: null,
	golongan: null,
	npwp: null,
	nomor: null,
	rekening_id: null,
	tanggalMulaiUsaha: null,
	luasBangunan: null,
	jamBukaUsaha: 11,
	jamTutupUsaha: 10,
	pengunjung: null,
	omsetOp: null,
	genset: true,
	airTanah: true,
	detailPotensiOp: {
		nama: null,
		nop: null,
		alamat: null,
		rtRw: null,
		kecamatan_id: null,
		kelurahan_id: null,
		telp: null
	}, 
	detailPajaks:[], 
	potensiPemilikWps:[], 
	potensiNarahubungs:[],
}
