sptpd = {
	npwpd_id: null,
	npwpd: {},
	objekPajak_id: null,
	objekPajak: {
		kelurahan:{},
		kecamatan:{},
	},
	rekening_id: null,
	rekening: {},
	periodeAwal: new Date(),
	periodeAkhir: new Date(),
	jatuhTempo: new Date(),
	attachment: null,
	omset: 0,
	detailSptHotel: {},
	detailSptResto: {},
	detailSptHiburan: {},
	detailSptReklame: {},
	detailSptParkir: {},
	detailSptAirTanah: {},
	detailSptPeneranganJalan: {},
}
