regNpwpdDetail = {
	jenisPajak: null,
	golongan: null,
	npwp: null,
	npwpd: null,
	tanggalPengukuhan: null,
	tanggalNpwpd: null,
	rekening_id: null,
	rekening: { },
	tanggalMulaiUsaha: null,
	luasBangunan: null,
	jamBukaUsaha: null,
	jamTutupUsaha: null,
	pengunjung: null,
	omsetOp: null,
	genset: null,
	airTanah: null,
	regObjekPajak:{
		nama: null,
		nop: null,
		alamat: null,
		rtRw: null,
		kecamatan_id: null,
		kelurahan_id: null,
		telp: ''
	}, 
	detail_op:[], 
	pemilik:[], 
	narahubung:[], 
}
