skkakanwil = {
    kanwil_id: null, 
    kpbb_id: null,
    provinsi_kode: null,
	daerah_kode: null,
	kecamatan_kode: null,
	kelurahan_kode: null,
    namaPropinsi: null,
    namaKota: null,
    namaKecamatan: null,
    namaKelurahan: null,
    typeLaporan: null,
	tahun: null,
	nomor: null,
	tanggal: null,
    jenis: null,	
    tglCetak: null,
    nipCetak: null,
}