entryDto = {
  id: null,
  parent_id: null,
  tipe: null,
  kelompok: null,
  jenis: null,
  objek: null,
  rincian: null,
  sub1: null,
  sub2: null,
  sub3: null,
  kode: null,
  nama: null,
  level: null,
  kodeJenisPajak: null,
  kodeVaJatim: null,
  kodeBilling: null,
  kodeJenisUsaha: null,
  jenisUsaha: null,
};
