pendaftaran = {
	jenisPajak: null,
	golongan: null,
	npwp: null,
	nomor: null,
	// nomorRegistrasi: null,
	isNomorRegistrasiAuto: true,
	npwpd: null,
	tanggalPengukuhan: null,
	tanggalNpwpd: null,
	rekening_id: null,
	tanggalMulaiUsaha: null,
	luasBangunan: null,
	jamBukaUsaha: null,
	jamTutupUsaha: null,
	pengunjung: null,
	omsetOp: null,
	genset: null,
	airTanah: null,
	objekPajak:{
		nama: null,
		nop: null,
		alamat: null,
		rtRw: null,
		kecamatan_id: null,
		kelurahan_id: null,
		telp: null
	}, 
	detailObjekPajak:[], 
	pemilik:[], 
	narahubung:[],
}
