pendaftaran = {
	jenisPajak: '',
	golongan: 0,
	npwp: '',
	npwpd: '',
	tanggalPengukuhan: new Date(),
	tanggalNpwpd:  new Date(),
	rekening_id: 0,
	rekening: { },
	tanggalMulaiUsaha:  new Date(),
	luasBangunan: '',
	jamBukaUsaha: '',
	jamTutupUsaha: '',
	pengunjung: '',
	omsetOp: '',
	genset: null,
	airTanah: null,
	objekPajak:{
		nama: '',
		nop: '',
		alamat: '',
		rtRw: '',
		kecamatan_id: 0,
		kelurahan_id: 0,
		telp: ''
	}, 
	detail_op:[], 
	pemilik:[], 
	narahubung:[], 
}
