objekPjakBangunanCreate = {
	provinsi_kode: null,
	daerah_kode: null,
	kecamatan_kode: null,
	kelurahan_kode: null,
	blok_kode: null,
	noUrut: null,
	jenisOp: null,
	noBangunan: null,
	jmlLantaiBng: null,
	jpb_Kode: null,
	noFormulirSpop: null,
	tahunDibangun: null,
	tahunRenovasi: null,
	luasBangunan: null,
	dayaListrik: null, //
	jmlAcSplit: null, //
	jmlAcWindow: null, //
	kondisi: null,
	jenisKonstruksi: null,
	jenisAtap: null,
	kodeDinding: null,
	kodeLantai: null,
	kodeLangitLangit: null,
	nilaiSistem: null,
	jenisTransaksi: null,
	panjangPagar: null,
	bahanPagar: null,
	tanggalPerekaman: null,
	perekam_pegawai_nip: null,
	tanggalPendataan: null,
	pendata_pegawai_nip: null,
	tanggalPemeriksaan: null,
	pemeriksa_pegawai_nip: null,
	nop: null,
	fasilitasBangunans: null,
}
