// the main purpose is for the group managemen
// [path, path view, title, depth, selected]
var menuArray = [
	['/pelayanan', '/Pelayanan', 'Pelayanan', 1, false],
	['/pelayanan/data-permohonan', '/Pelayanan/Data Permohonan', 'Data Permohonan', 2, false],
	['/pendaftaran', '/Pendaftaran', 'Pendaftaran', 1, false],
	['/pendaftaran/wajib-pajak', '/Pendaftaran/Pendaftaran Wajib Pajak', 'Pendaftaran Wajib Pajak', 2, false],
	['/pendaftaran/verifikasi-user-wp', '/Pendaftaran/Verifikasi Pendaftaran User WP', 'Verifikasi Pendaftaran User WP', 2, false],
	['/pendaftaran/verifikasi-npwpd', '/Pendaftaran/Verifikasi Pendaftaran NPWPD', 'Verifikasi Pendaftaran NPWPD', 2, false],
	['/pendaftaran/assigntment-npwpd', '/Pendaftaran/Assigntment NPWPD', 'Assigntment NPWPD', 2, false],
	['/pendataan', '/Pendataan', 'Pendataan', 1, false],
	['/pendataan/potensi-owp-baru', '/Pendataan/Potensi Objek/Wajib Pajak Baru', 'Potensi Objek/Wajib Pajak Baru', 2, false],
	['/pendataan/kunjungan', '/Pendataan/Kunjungan Pendataan', 'Kunjungan Pendataan', 2, false],
	['/pendataan/spopLspop', '/Pendataan/SPOP/LSPOP', 'SPOP/LSPOP', 2, false],
	['/pendataan/spopLspop/daftar', '/Pendataan/SPOP/LSPOP/Daftar SPOP/LSPOP', 'Daftar SPOP/LSPOP', 3, false],
	['/pendataan/spopLspop/verifikasi', '/Pendataan/SPOP/LSPOP/Verifikasi e-SPOP/e-LSPOP', 'Verifikasi e-SPOP/e-LSPOP', 3, false],
	['/pendataan/spopLspop/info-rinci-sppt', '/Pendataan/SPOP/LSPOP/Informasi Rinci SPPT', 'Informasi Rinci SPPT', 3, false],
	['/pendataan/obyekPajak', '/Pendataan/Pendataan Obyek Pajak', 'Pendataan Obyek Pajak', 2, false],
	['/pendataan/obyekPajak/updating-jalan-standar', '/Pendataan/Pendataan Obyek Pajak/Updating Jalan Standar', 'Updating Jalan Standar', 3, false],
	['/pendataan/obyekPajak/rencana-pendataan', '/Pendataan/Pendataan Obyek Pajak/Rencana Pendataan', 'Rencana Pendataan', 3, false],
	['/pendataan/laporan', '/Pendataan/Laporan Pendataan OP', 'Laporan Pendataan OP', 2, false],
	['/pendataan/laporan/tabel-referensi', '/Pendataan/Laporan Pendataan OP/Laporan Tabel-Tabel Referensi', 'Laporan Tabel-Tabel Referensi', 3, false],
	['/pendataan/laporan/data-op', '/Pendataan/Laporan Pendataan OP/Laporan Data OP', 'Laporan Data OP', 3, false],
	['/pendataan/laporan/sk-ka-kanwil', '/Pendataan/Laporan Pendataan OP/Laporan SK Ka. Kanwil', 'Laporan SK Ka. Kanwil', 3, false],
	['/pendataan/pemekaran-wilayah', '/Pendataan/Pemekaran Wilayah', 'Pemekaran Wilayah', 2, false],
	['/pendataan/reklas', '/Pendataan/Reklas', 'Reklas', 2, false],
	['/pendataan/pemberian-flag-njoptkp', '/Pendataan/Pemberian Flag NJOPTKP', 'Pemberian Flag NJOPTKP', 2, false],
	['/pendataan/update-rt-rw-massal', '/Pendataan/Update RT/RW Massal', 'Update RT/RW Massal', 2, false],
	['/pendataan/nilai-individu-lk-sistem', '/Pendataan/Daftar Nilai Individu < Nilai Sistem', 'Daftar Nilai Individu < Nilai Sistem', 2, false],
	['/pendataan/sin', '/Pendataan/SIN', 'SIN', 2, false],
	['/pendataan/sin/orang-pribadi-badan', '/Pendataan/SIN/Orang Pribadi dan Badan', 'Orang Pribadi dan Badan', 3, false],
	['/pendataan/sin/aset-negara-aset-daerah', '/Pendataan/SIN/Aset Negara Aset Daerah', 'Aset Negara Aset Daerah', 3, false],
	['/pendataan/relasi-nop-npwpd', '/Pendataan/Relasi NOP-NPWPD', 'Relasi NOP-NPWPD', 2, false],
	['/pendataan/znt', '/Pendataan/Pembuatan ZNT', 'Pembuatan ZNT', 2, false],
	['/pendataan/znt/pembuatan-tabel-blok', '/Pendataan/Pembuatan ZNT/Pembuatan Tabel Blok', 'Pembuatan Tabel Blok', 3, false],
	['/pendataan/znt/perubahan-nir', '/Pendataan/Pembuatan ZNT/Perubahan NIR', 'Perubahan NIR', 3, false],
	['/pendataan/znt/pembuatan-tabel-peta-znt', '/Pendataan/Pembuatan ZNT/Pembuatan Tabel Peta ZNT', 'Pembuatan Tabel Peta ZNT', 3, false],
	['/pendataan/znt/perubahan-znt-massal', '/Pendataan/Pembuatan ZNT/Perubahan ZNT Massal', 'Perubahan ZNT Massal', 3, false],
	['/pendataan/dbkb', '/Pendataan/Pembuatan DBKB', 'Pembuatan DBKB', 2, false],
	['/pendataan/dbkb/standar', '/Pendataan/Pembuatan DBKB/DBKB Standar', 'DBKB Standar', 3, false],
	['/pendataan/dbkb/standar/fasilitas-umum', '/Pendataan/Pembuatan DBKB/DBKB Standar/DBKB Fasilitas Umum', 'DBKB Fasilitas Umum', 4, false],
	['/pendataan/dbkb/nonStandar', '/Pendataan/Pembuatan DBKB/DBKB Non Standar', 'DBKB Non Standar', 3, false],
	['/pendataan/dbkb/nonStandar/jpb-2', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 2', 'DBKB JPB 2', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-3', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 3', 'DBKB JPB 3', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-4', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 4', 'DBKB JPB 4', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-5', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 5', 'DBKB JPB 5', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-6', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 6', 'DBKB JPB 6', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-7', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 7', 'DBKB JPB 7', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-8_a', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 8_A', 'DBKB JPB 8_A', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-8_b', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 8_B', 'DBKB JPB 8_B', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-9', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 9', 'DBKB JPB 9', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-12', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 12', 'DBKB JPB 12', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-13', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 13', 'DBKB JPB 13', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-14', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 14', 'DBKB JPB 14', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-15', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 15', 'DBKB JPB 15', 4, false],
	['/pendataan/dbkb/nonStandar/jpb-16', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB JPB 16', 'DBKB JPB 16', 4, false],
	['/pendataan/dbkb/nonStandar/mezzanin', '/Pendataan/Pembuatan DBKB/DBKB Non Standar/DBKB MEZZANIN', 'DBKB MEZZANIN', 4, false],
	['/pendataan/kelas-tanah', '/Pendataan/Kelas Tanah', 'Kelas Tanah', 2, false],
	['/pendataan/kelas-bangunan', '/Pendataan/Kelas Bangunan', 'Kelas Bangunan', 2, false],
	['/penetapan', '/Penetapan', 'Penetapan', 1, false],
	['/penetapan/verifikasiESptpd', '/Penetapan/Verifikasi e-SPTPD', 'Verifikasi e-SPTPD', 2, false],
	['/penetapan/verifikasiESptpd/pajak-hotel', '/Penetapan/Verifikasi e-SPTPD/Pajak Hotel', 'Pajak Hotel', 3, false],
	['/penetapan/verifikasiESptpd/pajak-resto', '/Penetapan/Verifikasi e-SPTPD/Pajak Resto', 'Pajak Resto', 3, false],
	['/penetapan/verifikasiESptpd/pajak-air-tanah', '/Penetapan/Verifikasi e-SPTPD/Pajak Air Tanah', 'Pajak Air Tanah', 3, false],
	['/penetapan/verifikasiESptpd/pajak-parkir', '/Penetapan/Verifikasi e-SPTPD/Pajak Parkir', 'Pajak Parkir', 3, false],
	['/penetapan/verifikasiESptpd/pajak-hiburan', '/Penetapan/Verifikasi e-SPTPD/Pajak Hiburan', 'Pajak Hiburan', 3, false],
	['/penetapan/verifikasiESptpd/pajak-penerangan-jalan', '/Penetapan/Verifikasi e-SPTPD/Pajak Penerangan Jalan', 'Pajak Penerangan Jalan', 3, false],
	['/penetapan/verifikasi-e-bphtb', '/Penetapan/Verifikasi e-BPHTB', 'Verifikasi e-BPHTB', 2, false],
	['/penetapan/validasi-e-bphtb', '/Penetapan/Validasi e-BPHTB', 'Validasi e-BPHTB', 2, false],
	['/penetapan/sptpd', '/Penetapan/SPTPD', 'SPTPD', 2, false],
	['/penetapan/sptpd/pajak-hotel', '/Penetapan/SPTPD/Pajak Hotel', 'Pajak Hotel', 3, false],
	['/penetapan/sptpd/pajak-resto', '/Penetapan/SPTPD/Pajak Resto', 'Pajak Resto', 3, false],
	['/penetapan/sptpd/pajak-air-tanah', '/Penetapan/SPTPD/Pajak Air Tanah', 'Pajak Air Tanah', 3, false],
	['/penetapan/sptpd/pajak-parkir', '/Penetapan/SPTPD/Pajak Parkir', 'Pajak Parkir', 3, false],
	['/penetapan/sptpd/pajak-hiburan', '/Penetapan/SPTPD/Pajak Hiburan', 'Pajak Hiburan', 3, false],
	['/penetapan/sptpd/pajak-penerangan-jalan', '/Penetapan/SPTPD/Pajak Penerangan Jalan', 'Pajak Penerangan Jalan', 3, false],
	['/penetapan/skpd', '/Penetapan/SKPD', 'SKPD', 2, false],
	['/penetapan/skpd/pajak-reklame', '/Penetapan/SKPD/Pajak Reklame', 'Pajak Reklame', 3, false],
	['/penetapan/skpd/pajak-hotel', '/Penetapan/SKPD/Pajak Hotel', 'Pajak Hotel', 3, false],
	['/penetapan/skpd/pajak-resto', '/Penetapan/SKPD/Pajak Resto', 'Pajak Resto', 3, false],
	['/penetapan/skpd/pajak-air-tanah', '/Penetapan/SKPD/Pajak Air Tanah', 'Pajak Air Tanah', 3, false],
	['/penetapan/skpd/pajak-parkir', '/Penetapan/SKPD/Pajak Parkir', 'Pajak Parkir', 3, false],
	['/penetapan/skpd/pajak-hiburan', '/Penetapan/SKPD/Pajak Hiburan', 'Pajak Hiburan', 3, false],
	['/penetapan/skpd/pajak-penerangan-jalan', '/Penetapan/SKPD/Pajak Penerangan Jalan', 'Pajak Penerangan Jalan', 3, false],
	['/penetapan/skpdkbSkpdkbt', '/Penetapan/SKPDKB/SKPDKBT', 'SKPDKB/SKPDKBT', 2, false],
	['/penetapan/skpdkbSkpdkbt/sa', '/Penetapan/SKPDKB/SKPDKBT/SA', 'SA', 3, false],
	['/penetapan/skpdkbSkpdkbt/oa', '/Penetapan/SKPDKB/SKPDKBT/OA', 'OA', 3, false],
	['/penetapan/skpdlb', '/Penetapan/Surat Ketetapan Pajak Daerah Lebih Bayar', 'Surat Ketetapan Pajak Daerah Lebih Bayar', 2, false],
	['/penetapan/massalSkpdkb', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar', 'Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar', 2, false],
	['/penetapan/massalSkpdkb/pajak-reklame', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar/Pajak Reklame', 'Pajak Reklame', 3, false],
	['/penetapan/massalSkpdkb/pajak-hotel', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar/Pajak Hotel', 'Pajak Hotel', 3, false],
	['/penetapan/massalSkpdkb/pajak-resto', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar/Pajak Resto', 'Pajak Resto', 3, false],
	['/penetapan/massalSkpdkb/pajak-air-tanah', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar/Pajak Air Tanah', 'Pajak Air Tanah', 3, false],
	['/penetapan/massalSkpdkb/pajak-parkir', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar/Pajak Parkir', 'Pajak Parkir', 3, false],
	['/penetapan/massalSkpdkb/pajak-hiburan', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar/Pajak Hiburan', 'Pajak Hiburan', 3, false],
	['/penetapan/massalSkpdkb/pajak-penerangan-jalan', '/Penetapan/Penetapan Massal Surat Ketetapan Pajak Daerah/ Surat Ketetapan Pajak Daerah Kurang Bayar/Pajak Penerangan Jalan', 'Pajak Penerangan Jalan', 3, false],
	['/penetapan/terseleksi-pbb', '/Penetapan/Penetapan Terseleksi PBB', 'Penetapan Terseleksi PBB', 2, false],
	['/penetapan/penilaianPenetapanCetakMassalPbb', '/Penetapan/Penilaian, Penetapan dan Cetak Massal PBB', 'Penilaian, Penetapan dan Cetak Massal PBB', 2, false],
	['/penetapan/penilaianPenetapanCetakMassalPbb/cetak-massal-sppt', '/Penetapan/Penilaian, Penetapan dan Cetak Massal PBB/Cetak Massal SPPT PBB', 'Cetak Massal SPPT PBB', 3, false],
	['/penetapan/penilaianPenetapanCetakMassalPbb/copy-dbkb-znt-tp-sppt-masal', '/Penetapan/Penilaian, Penetapan dan Cetak Massal PBB/Copy DBKB. ZNT. TP SPPT Masal Tahun Sebelumnya', 'Copy DBKB. ZNT. TP SPPT Masal Tahun Sebelumnya', 3, false],
	['/penetapan/simulasi-penetapan-massal-pbb', '/Penetapan/Simulasi Penetapan Massal PBB', 'Simulasi Penetapan Massal PBB', 2, false],
	['/penetapan/salinan-sppt-pbb', '/Penetapan/Salinan SPPT PBB', 'Salinan SPPT PBB', 2, false],
	['/penetapan/sppt-terseleksi', '/Penetapan/Penetapan SPPT Terseleksi', 'Penetapan SPPT Terseleksi', 2, false],
	['/penetapan/infoSpptSkp', '/Penetapan/Informasi SPPT/SKP', 'Informasi SPPT/SKP', 2, false],
	['/penetapan/infoSpptSkp/relasi-op-sp', '/Penetapan/Informasi SPPT/SKP/Informasi Relasi Objek Pajak Dengan Subyek Pajak', 'Informasi Relasi Objek Pajak Dengan Subyek Pajak', 3, false],
	['/penetapan/infoSpptSkp/rinci-skp-spop', '/Penetapan/Informasi SPPT/SKP/Informasi RInci SKP Terhadap SPOP', 'Informasi RInci SKP Terhadap SPOP', 3, false],
	['/penetapan/infoSpptSkp/rinci-skp-kurang-byr', '/Penetapan/Informasi SPPT/SKP/Informasi Rinci SKP Kurang Bayar', 'Informasi Rinci SKP Kurang Bayar', 3, false],
	['/penetapan/infoSpptSkp/pbb-lebih-kurang-byr', '/Penetapan/Informasi SPPT/SKP/Daftar PBB Lebih atau Kurang Bayar', 'Daftar PBB Lebih atau Kurang Bayar', 3, false],
	['/penetapan/perubahanSpptSkp', '/Penetapan/Perubahan SPPT/SKP', 'Perubahan SPPT/SKP', 2, false],
	['/penetapan/perubahanSpptSkp/pembetulan', '/Penetapan/Perubahan SPPT/SKP/Pembetulan SPPT/SKP', 'Pembetulan SPPT/SKP', 3, false],
	['/penetapan/perubahanSpptSkp/pembetulan/input-tungal', '/Penetapan/Perubahan SPPT/SKP/Pembetulan SPPT/SKP/Input SK Pembetulan Tunggal', 'Input SK Pembetulan Tunggal', 4, false],
	['/penetapan/perubahanSpptSkp/pembetulan/proses-tunggal', '/Penetapan/Perubahan SPPT/SKP/Pembetulan SPPT/SKP/Proses SK Pembetulan Tunggal', 'Proses SK Pembetulan Tunggal', 4, false],
	['/penetapan/perubahanSpptSkp/pembetulan/input-kolektif', '/Penetapan/Perubahan SPPT/SKP/Pembetulan SPPT/SKP/Input SK Pembetulan Kolektif', 'Input SK Pembetulan Kolektif', 4, false],
	['/penetapan/perubahanSpptSkp/pembetulan/proses-kolektif', '/Penetapan/Perubahan SPPT/SKP/Pembetulan SPPT/SKP/Proses SK Pembetulan Kolektif', 'Proses SK Pembetulan Kolektif', 4, false],
	['/penetapan/perubahanSpptSkp/pembetulan/secara-jabatan', '/Penetapan/Perubahan SPPT/SKP/Pembetulan SPPT/SKP/Pembetulan Secara Jabatan', 'Pembetulan Secara Jabatan', 4, false],
	['/penetapan/perubahanSpptSkp/pembetulan/cetak-secara-jabatan', '/Penetapan/Perubahan SPPT/SKP/Pembetulan SPPT/SKP/Proses Cetak Pembetulan Secara Jabatan', 'Proses Cetak Pembetulan Secara Jabatan', 4, false],
	['/penetapan/perubahanSpptSkp/batal', '/Penetapan/Perubahan SPPT/SKP/Pembatalan SPPT/SKP', 'Pembatalan SPPT/SKP', 3, false],
	['/penetapan/perubahanSpptSkp/batal/input-tunggal', '/Penetapan/Perubahan SPPT/SKP/Pembatalan SPPT/SKP/Input SK Pembatalan Tunggal', 'Input SK Pembatalan Tunggal', 4, false],
	['/penetapan/perubahanSpptSkp/batal/proses-tunggal', '/Penetapan/Perubahan SPPT/SKP/Pembatalan SPPT/SKP/Proses SK Pembatalan Tunggal', 'Proses SK Pembatalan Tunggal', 4, false],
	['/penetapan/perubahanSpptSkp/batal/input-kolektif', '/Penetapan/Perubahan SPPT/SKP/Pembatalan SPPT/SKP/Input SK Pembatalan Kolektif', 'Input SK Pembatalan Kolektif', 4, false],
	['/penetapan/perubahanSpptSkp/batal/proses-kolektif', '/Penetapan/Perubahan SPPT/SKP/Pembatalan SPPT/SKP/Proses SK Pembatalan Kolektif', 'Proses SK Pembatalan Kolektif', 4, false],
	['/penetapan/penundaan-tanggal-jatuh-tempo', '/Penetapan/Penundaan Tanggal Jatuh Tempo', 'Penundaan Tanggal Jatuh Tempo', 2, false],
	['/penetapan/lapDistOp', '/Penetapan/Laporan Distribusi OP', 'Laporan Distribusi OP', 2, false],
	['/penetapan/lapDistOp/per-kelompok-jpb', '/Penetapan/Laporan Distribusi OP/OP Per Kelompok JPB', 'OP Per Kelompok JPB', 3, false],
	['/penetapan/lapDistOp/per-kelas', '/Penetapan/Laporan Distribusi OP/OP Per Kelas', 'OP Per Kelas', 3, false],
	['/penetapan/lapDistOp/perbandingan-kelas-per-desa-kelurahan', '/Penetapan/Laporan Distribusi OP/Perbandingan Kelas Per Desa/Kelurahan', 'Perbandingan Kelas Per Desa/Kelurahan', 3, false],
	['/penetapan/lapDistOp/per-group-ketetapan', '/Penetapan/Laporan Distribusi OP/OP Per Group Ketetapan', 'OP Per Group Ketetapan', 3, false],
	['/penetapan/lap-himpunan-ketetapan-pbb-njop', '/Penetapan/Laporan Himpunan Ketetapan PBB/NJOP', 'Laporan Himpunan Ketetapan PBB/NJOP', 2, false],
	['/penetapan/tanda-terima-sppt-skp-stp', '/Penetapan/Tanda Terima SPPT/SKP/STP', 'Tanda Terima SPPT/SKP/STP', 2, false],
	['/penetapan/penilaian', '/Penetapan/Penilaian', 'Penilaian', 2, false],
	['/penetapan/penilaian/massal', '/Penetapan/Penilaian/Penilaian Massal', 'Penilaian Massal', 3, false],
	['/penetapan/penilaian/laporan', '/Penetapan/Penilaian/Laporan Penilaian', 'Laporan Penilaian', 3, false],
	['/petaPajak', '/Peta Pajak', 'Peta Pajak', 1, false],
	['/petaPajak/kelas-bangunan', '/Peta Pajak/Peta Kelas Bangunan', 'Peta Kelas Bangunan', 2, false],
	['/petaPajak/jenis-tanah', '/Peta Pajak/Peta Jenis Tanah', 'Peta Jenis Tanah', 2, false],
	['/petaPajak/jenis-peruntukan-bangunan', '/Peta Pajak/Peta Jenis Peruntukan Bangunan', 'Peta Jenis Peruntukan Bangunan', 2, false],
	['/petaPajak/znt', '/Peta Pajak/Peta ZNT', 'Peta ZNT', 2, false],
	['/petaPajak/tunggakan-pajak', '/Peta Pajak/Peta Tunggakan Pajak', 'Peta Tunggakan Pajak', 2, false],
	['/petaPajak/objek-pajak', '/Peta Pajak/Peta Objek Pajak', 'Peta Objek Pajak', 2, false],
	['/petaPajak/fasum-fasos', '/Peta Pajak/Peta Fasum/Fasos', 'Peta Fasum/Fasos', 2, false],
	['/petaPajak/reklame', '/Peta Pajak/Peta Reklame', 'Peta Reklame', 2, false],
	['/petaPajak/pdl', '/Peta Pajak/Peta PDL', 'Peta PDL', 2, false],
	['/petaPajak/cetak-peta', '/Peta Pajak/Cetak Peta', 'Cetak Peta', 2, false],
	['/penagihanPemeriksaan', '/Penagihan dan Pemeriksaan', 'Penagihan dan Pemeriksaan', 1, false],
	['/penagihanPemeriksaan/surat-tagihan-pd', '/Penagihan dan Pemeriksaan/Surat Tagihan Pajak Daerah', 'Surat Tagihan Pajak Daerah', 2, false],
	['/penagihanPemeriksaan/und-pemeriksaan', '/Penagihan dan Pemeriksaan/Undangan Pemeriksaan', 'Undangan Pemeriksaan', 2, false],
	['/penagihanPemeriksaan/bapp', '/Penagihan dan Pemeriksaan/Berita Acara Penagihan/Pemeriksaan', 'Berita Acara Penagihan/Pemeriksaan', 2, false],
	['/penagihanPemeriksaan/jurnal-piutang', '/Penagihan dan Pemeriksaan/Jurnal Piutang', 'Jurnal Piutang', 2, false],
	['/penagihanPemeriksaan/penagihan', '/Penagihan dan Pemeriksaan/Penagihan', 'Penagihan', 2, false],
	['/penagihanPemeriksaan/penagihan/tunggakan', '/Penagihan dan Pemeriksaan/Penagihan/Daftar Tunggakan', 'Daftar Tunggakan', 3, false],
	['/penagihanPemeriksaan/penagihan/tunggakan/lap-op-tunggakan', '/Penagihan dan Pemeriksaan/Penagihan/Daftar Tunggakan/Laporan OP Tunggakan', 'Laporan OP Tunggakan', 4, false],
	['/penagihanPemeriksaan/penagihan/pengeluaran-himbauan', '/Penagihan dan Pemeriksaan/Penagihan/Pengeluaran Himbauan', 'Pengeluaran Himbauan', 3, false],
	['/penagihanPemeriksaan/pencabutan-dan-surat-sita', '/Penagihan dan Pemeriksaan/Pencabutan dan Pencetakan Surat Sita', 'Pencabutan dan Pencetakan Surat Sita', 2, false],
	['/jaminan-bongkar-reklame', '/Jaminan Bongkar Reklame', 'Jaminan Bongkar Reklame', 1, false],
	['/bendahara', '/Bendahara', 'Bendahara', 1, false],
	['/bendahara/surat-setoran-pajak-daerah', '/Bendahara/Surat Setoran Pajak Daerah', 'Surat Setoran Pajak Daerah', 2, false],
	['/bendahara/sinkronisasi-data-pembayaran-bank', '/Bendahara/Sinkronisasi Data Pembayaran Bank', 'Sinkronisasi Data Pembayaran Bank', 2, false],
	['/bendahara/surat-tanda-setoran', '/Bendahara/Surat Tanda Setoran', 'Surat Tanda Setoran', 2, false],
	['/bendahara/pembayaran/pencatatan', '/Bendahara/Pembayaran', 'Pembayaran', 2, false],
	['/bendahara/pembayaran/pencatatan', '/Bendahara/Pembayaran/Pencatatan Pembayaran', 'Pencatatan Pembayaran', 3, false],
	['/bendahara/pembayaran/pencatatan/tunggal', '/Bendahara/Pembayaran/Pencatatan Pembayaran/Pencatatan Tunggal', 'Pencatatan Tunggal', 4, false],
	['/bendahara/pembayaran/pencatatan/ssp-pbb', '/Bendahara/Pembayaran/Pencatatan Pembayaran/Pencatatan SSP PBB', 'Pencatatan SSP PBB', 4, false],
	['/bendahara/pembayaran/pencatatan/surat-ket-pembayaran-elektro', '/Bendahara/Pembayaran/Pencatatan Pembayaran/Surat Keterangan Pembayaran Elektronik', 'Surat Keterangan Pembayaran Elektronik', 4, false],
	['/bendahara/pembayaran-bphtb', '/Bendahara/Pembayaran BPHTB', 'Pembayaran BPHTB', 2, false],
	['/bendahara/tempatPembayaran', '/Bendahara/Tempat Pembayaran', 'Tempat Pembayaran', 2, false],
	['/bendahara/tempatPembayaran/elektro', '/Bendahara/Tempat Pembayaran/Tempat pembayaran elektronik', 'Tempat pembayaran elektronik', 3, false],
	['/bendahara/tempatPembayaran/elektro/update-va-satuan', '/Bendahara/Tempat Pembayaran/Tempat pembayaran elektronik/Update VA satuan', 'Update VA satuan', 4, false],
	['/pengurangan', '/Pengurangan', 'Pengurangan', 1, false],
	['/keberatan', '/Keberatan', 'Keberatan', 1, false],
	['/keberatan/verifikasi', '/Keberatan/Varifikasi / Validasi', 'Varifikasi / Validasi', 2, false],
	['/keberatan/penyelesaianPermohonan', '/Keberatan/Penyelesaian Permohonan Keberatan', 'Penyelesaian Permohonan Keberatan', 2, false],
	['/keberatan/penyelesaianPermohonan/input', '/Keberatan/Penyelesaian Permohonan Keberatan/Input SK Keberatan PBB', 'Input SK Keberatan PBB', 3, false],
	['/keberatan/penyelesaianPermohonan/cetak', '/Keberatan/Penyelesaian Permohonan Keberatan/Mencetak SK Keberatan', 'Mencetak SK Keberatan', 3, false],
	['/keberatan/pembetulanSk', '/Keberatan/Pembetulan SK Keberatan', 'Pembetulan SK Keberatan', 2, false],
	['/keberatan/pembetulanSk/input', '/Keberatan/Pembetulan SK Keberatan/Input Pembetulan SK Keberatan PBB', 'Input Pembetulan SK Keberatan PBB', 3, false],
	['/keberatan/pembetulanSk/cetak', '/Keberatan/Pembetulan SK Keberatan/Mencetak Pembetulan SK Keberatan PBB', 'Mencetak Pembetulan SK Keberatan PBB', 3, false],
	['/restitusi', '/Restitusi', 'Restitusi', 1, false],
	['/restitusi/pajak-daerah', '/Restitusi/Restitusi Pajak Daerah', 'Restitusi Pajak Daerah', 2, false],
	['/restitusi/pemindahbukuan-pembayaran', '/Restitusi/Pemindahbukuan Pembayaran', 'Pemindahbukuan Pembayaran', 2, false],
	['/ppat', '/PPAT', 'PPAT', 1, false],
	['/ppat/manajemen-user-ppat', '/PPAT/Manajemen User PPAT', 'Manajemen User PPAT', 2, false],
	['/ppat/lap-ppat', '/PPAT/Daftar Laporan PPAT', 'Daftar Laporan PPAT', 2, false],
	['/ppat/transaksi-ppat', '/PPAT/Daftar Transaksi PPAT', 'Daftar Transaksi PPAT', 2, false],
	['/ppat/ringkasan-bulanan-transaksi-ppat', '/PPAT/Ringkasan Bulanan Transaksi PPAT', 'Ringkasan Bulanan Transaksi PPAT', 2, false],
	['/pelaporan', '/Pelaporan', 'Pelaporan', 1, false],
	['/pelaporan/penerimaan', '/Pelaporan/Penerimaan', 'Penerimaan', 2, false],
	['/pelaporan/setoran', '/Pelaporan/Setoran', 'Setoran', 2, false],
	['/pelaporan/target-realisasi', '/Pelaporan/Target dan Realisasi', 'Target dan Realisasi', 2, false],
	['/pelaporan/target-realisasi-per-jenis-pajak', '/Pelaporan/Target dan Realisasi per Jenis Pajak', 'Target dan Realisasi per Jenis Pajak', 2, false],
	['/pelaporan/rincian-wajib-pajak-objek-pajak', '/Pelaporan/Rincian Wajib Pajak/Objek Pajak', 'Rincian Wajib Pajak/Objek Pajak', 2, false],
	['/pelaporan/buku-pembantu-penerimaan-sejenis-via-bank', '/Pelaporan/Buku Pembantu Penerimaan Sejenis via Bank', 'Buku Pembantu Penerimaan Sejenis via Bank', 2, false],
	['/pelaporan/buku-pembantu-per-rincian-objek-penerimaan', '/Pelaporan/Buku Pembantu Per Rincian Objek Penerimaan', 'Buku Pembantu Per Rincian Objek Penerimaan', 2, false],
	['/pelaporan/buku-rekap-penerimaan-hbt', '/Pelaporan/Buku Rekapitulasi Penerimaan Harian/Bulanan/Tahunan', 'Buku Rekapitulasi Penerimaan Harian/Bulanan/Tahunan', 2, false],
	['/pelaporan/buku-kas-umum-penerimaan', '/Pelaporan/Buku Kas Umum Penerimaan', 'Buku Kas Umum Penerimaan', 2, false],
	['/customerService', '/Customer Service', 'Customer Service', 1, false],
	['/customerService/chat', '/Customer Service/Chat Customer Service', 'Chat Customer Service', 2, false],
	['/konfigurasi', '/Konfigurasi', 'Konfigurasi', 1, false],
	['/konfigurasi/manajemenUser', '/Konfigurasi/Manajemen User', 'Manajemen User', 2, false],
	['/konfigurasi/manajemenUser/user', '/Konfigurasi/Manajemen User/User', 'User', 3, false],
	['/konfigurasi/manajemenUser/group', '/Konfigurasi/Manajemen User/Group', 'Group', 3, false],
	['/konfigurasi/dataRef', '/Konfigurasi/Data Referensi', 'Data Referensi', 2, false],
	['/konfigurasi/dataRef/wilayah', '/Konfigurasi/Data Referensi/Wilayah', 'Wilayah', 3, false],
	['/konfigurasi/dataRef/tempat-pembayaran-sppt-massal', '/Konfigurasi/Data Referensi/Tempat Pembayaran SPPT Massal', 'Tempat Pembayaran SPPT Massal', 3, false],
	['/konfigurasi/dataRef/resource', '/Konfigurasi/Data Referensi/Resource', 'Resource', 3, false],
	['/konfigurasi/dataRef/resource/harga', '/Konfigurasi/Data Referensi/Resource/Harga Resource', 'Harga Resource', 4, false],
	['/konfigurasi/dataRef/resource/lap-harga', '/Konfigurasi/Data Referensi/Resource/Laporan Harga Resource', 'Laporan Harga Resource', 4, false],
	['/konfigurasi/dataRef/buku-njoptkp-tarif', '/Konfigurasi/Data Referensi/Buku/NJOPTKP/Tarif', 'Buku/NJOPTKP/Tarif', 3, false],
	['/konfigurasi/dataRef/kantor-lelang', '/Konfigurasi/Data Referensi/Kantor Lelang', 'Kantor Lelang', 3, false],
	['/konfigurasi/dataRef/ref-umum', '/Konfigurasi/Data Referensi/Ref Umum', 'Ref Umum', 3, false],
	['/konfigurasi/dataRef/parameter-keluaran-pst', '/Konfigurasi/Data Referensi/Parameter Keluaran PST', 'Parameter Keluaran PST', 3, false],
	['/konfigurasi/dataRef/master', '/Konfigurasi/Data Referensi/Master Data', 'Master Data', 3, false],
	['/konfigurasi/dataRef/master/nop', '/Konfigurasi/Data Referensi/Master Data/NOP', 'NOP', 4, false],
	['/konfigurasi/dataRef/master/ppat', '/Konfigurasi/Data Referensi/Master Data/PPAT', 'PPAT', 4, false],
	['/konfigurasi/dataRef/master/nik', '/Konfigurasi/Data Referensi/Master Data/NIK', 'NIK', 4, false],
	['/konfigurasi/dataRef/master/provinsi', '/Konfigurasi/Data Referensi/Master Data/Provinsi', 'Provinsi', 4, false],
	['/konfigurasi/dataRef/master/kabupaten', '/Konfigurasi/Data Referensi/Master Data/Kabupaten', 'Kabupaten', 4, false],
	['/konfigurasi/dataRef/master/kecamatan', '/Konfigurasi/Data Referensi/Master Data/Kecamatan', 'Kecamatan', 4, false],
	['/konfigurasi/dataRef/master/kelurahan', '/Konfigurasi/Data Referensi/Master Data/Kelurahan', 'Kelurahan', 4, false],
	['/konfigurasi/dataRef/master/bank-user', '/Konfigurasi/Data Referensi/Master Data/Bank User', 'Bank User', 4, false],
	['/konfigurasi/dataRef/master/jenis-perolehan', '/Konfigurasi/Data Referensi/Master Data/Jenis Perolehan', 'Jenis Perolehan', 4, false],
	['/konfigurasi/dataRef/master/refrensi-bank', '/Konfigurasi/Data Referensi/Master Data/Daftar Refrensi Bank', 'Daftar Refrensi Bank', 4, false],
	['/konfigurasi/dataRef/master/pegawai', '/Konfigurasi/Data Referensi/Master Data/Pegawai', 'Pegawai', 4, false],
	['/konfigurasi/dataRef/master/satuan-kerja', '/Konfigurasi/Data Referensi/Master Data/Satuan Kerja', 'Satuan Kerja', 4, false],
	['/konfigurasi/dataRef/master/rekening', '/Konfigurasi/Data Referensi/Master Data/Rekening', 'Rekening', 4, false],
	['/konfigurasi/dataRef/master/anggaran', '/Konfigurasi/Data Referensi/Master Data/Anggaran', 'Anggaran', 4, false],
	['/konfigurasi/dataRef/master/sumber-dana', '/Konfigurasi/Data Referensi/Master Data/Sumber Dana', 'Sumber Dana', 4, false],
	['/konfigurasi/dataRef/master/bendahara', '/Konfigurasi/Data Referensi/Master Data/Bendahara', 'Bendahara', 4, false],
	['/konfigurasi/dataRef/master/jurnal', '/Konfigurasi/Data Referensi/Master Data/Jurnal', 'Jurnal', 4, false],
	['/konfigurasi/dataRef/master/harga-ref', '/Konfigurasi/Data Referensi/Master Data/Harga Referensi', 'Harga Referensi', 4, false],
	['/konfigurasi/lihat', '/Konfigurasi/Lihat', 'Lihat', 2, false],
	['/konfigurasi/lihat/tabel', '/Konfigurasi/Lihat/Tabel', 'Tabel', 3, false],
	['/konfigurasi/lihat/tabel/znt', '/Konfigurasi/Lihat/Tabel/ZNT', 'ZNT', 4, false],
	['/konfigurasi/lihat/tabel/jalan-std', '/Konfigurasi/Lihat/Tabel/Jalan Standart', 'Jalan Standart', 4, false],
	['/konfigurasi/lihat/tabel/tempat-pembayaran', '/Konfigurasi/Lihat/Tabel/Tempat Pembayaran', 'Tempat Pembayaran', 4, false],
	['/konfigurasi/lihat/tabel/surat-kep', '/Konfigurasi/Lihat/Tabel/Surat Keputusan', 'Surat Keputusan', 4, false],
	['/konfigurasi/lihat/penetapan', '/Konfigurasi/Lihat/Penetapan', 'Penetapan', 3, false],
	['/konfigurasi/lihat/penetapan/tagihan-tidak-sampai', '/Konfigurasi/Lihat/Penetapan/Daftar Tagihan Tidak Sampai', 'Daftar Tagihan Tidak Sampai', 4, false],
	['/konfigurasi/lihat/penetapan/tegoran-diterbitkan', '/Konfigurasi/Lihat/Penetapan/Daftar Tegoran Diterbitkan', 'Daftar Tegoran Diterbitkan', 4, false],
	['/konfigurasi/lihat/penetapan/penerimaan', '/Konfigurasi/Lihat/Penetapan/Daftar Penerimaan', 'Daftar Penerimaan', 4, false],
	['/konfigurasi/lihat/penetapan/tunggakan', '/Konfigurasi/Lihat/Penetapan/Daftar Tunggakan', 'Daftar Tunggakan', 4, false],
	['/konfigurasi/lihat/kinerjaOrg', '/Konfigurasi/Lihat/Kinerja Organisasi', 'Kinerja Organisasi', 3, false],
	['/konfigurasi/lihat/kinerjaOrg/stat-kinerja-pelayanan', '/Konfigurasi/Lihat/Kinerja Organisasi/Statistik Kinerja Pelayanan', 'Statistik Kinerja Pelayanan', 4, false],
	['/konfigurasi/lihat/kinerjaOrg/rinci-pendataan-lapangan', '/Konfigurasi/Lihat/Kinerja Organisasi/Rincian Pendataan Lapangan', 'Rincian Pendataan Lapangan', 4, false],
	['/konfigurasi/lihat/kinerjaOrg/rinci-rekam-data', '/Konfigurasi/Lihat/Kinerja Organisasi/Rincian Perekaman Data', 'Rincian Perekaman Data', 4, false],
	['/konfigurasi/lihat/kinerjaOrg/rinci-rekam-stts', '/Konfigurasi/Lihat/Kinerja Organisasi/Rincian Perekaman STTS', 'Rincian Perekaman STTS', 4, false],
	['/konfigurasi/lihat/kinerjaOrg/rinci-rekam-td-terima-sppt', '/Konfigurasi/Lihat/Kinerja Organisasi/Rincian Perekaman Tanda Terima SPPT', 'Rincian Perekaman Tanda Terima SPPT', 4, false],
	['/konfigurasi/lihat/perubahan', '/Konfigurasi/Lihat/Daftar Perubahan', 'Daftar Perubahan', 3, false],
	['/konfigurasi/lihat/perubahan/data-op', '/Konfigurasi/Lihat/Daftar Perubahan/Daftar Perubahan Data OP', 'Daftar Perubahan Data OP', 4, false],
	['/konfigurasi/lihat/perubahan/tabel-znt', '/Konfigurasi/Lihat/Daftar Perubahan/Daftar Perubahan Tabel ZNT', 'Daftar Perubahan Tabel ZNT', 4, false],
	['/konfigurasi/lihat/sejarah', '/Konfigurasi/Lihat/Sejarah Objek Pajak', 'Sejarah Objek Pajak', 3, false],
	['/konfigurasi/lihat/sejarah/op', '/Konfigurasi/Lihat/Sejarah Objek Pajak/Sejarah Objek Pajak', 'Sejarah Objek Pajak', 4, false],
	['/konfigurasi/lihat/sejarah/sppt', '/Konfigurasi/Lihat/Sejarah Objek Pajak/Sejarah SPPT', 'Sejarah SPPT', 4, false],
	['/konfigurasi/lihat/nomor-pelayanan', '/Konfigurasi/Lihat/Nomor Pelayanan', 'Nomor Pelayanan', 3, false],
	['/konfigurasi/lihat/nop-terbesar', '/Konfigurasi/Lihat/NOP Terbesar', 'NOP Terbesar', 3, false],
	['/konfigurasi/lihat/perubahan-nop', '/Konfigurasi/Lihat/Perubahan NOP', 'Perubahan NOP', 3, false],
	['/konfigurasi/pajak', '/Konfigurasi/Konfigurasi Pajak', 'Konfigurasi Pajak', 2, false],
	['/konfigurasi/pembayaran', '/Konfigurasi/Konfigurasi Pembayaran', 'Konfigurasi Pembayaran', 2, false],
	['/konfigurasi/api', '/Konfigurasi/Konfigurasi API', 'Konfigurasi API', 2, false],
	['/konfigurasi/pengumuman', '/Konfigurasi/Pengumuman', 'Pengumuman', 2, false],
	['/konfigurasi/utilitas', '/Konfigurasi/Utilitas', 'Utilitas', 2, false],
	['/konfigurasi/utilitas/setting-session', '/Konfigurasi/Utilitas/Setting Session', 'Setting Session', 3, false],
	['/bphtb', '/BPHTB', 'BPHTB', 1, false],
	['/bphtb/lap-bphtb', '/BPHTB/Laporan BPHTB', 'Laporan BPHTB', 2, false],
	['/bphtb/pembayaran-sspd', '/BPHTB/Pembayaran SSPD', 'Pembayaran SSPD', 2, false],
	['/bphtb/kurang-byr-sspd', '/BPHTB/Kurang Bayar SSPD', 'Kurang Bayar SSPD', 2, false],
	['/bphtb/lap-penerimaan-bank', '/BPHTB/Laporan Penerimaan Bank', 'Laporan Penerimaan Bank', 2, false],
	['/bphtb/jumlah-transaksi-wp', '/BPHTB/Cek Jumlah Transaksi Wajib Pajak', 'Cek Jumlah Transaksi Wajib Pajak', 2, false],
	['/rak-berkas', '/Rak Berkas', 'Rak Berkas', 1, false],
];