entryDto = {
    id: null,
    nama: null,
    nip: null,
    jabatan_id: null,
    bidangKerja_kode: null,
    startDate: null,
    endDate: null,
    user_group_id: null,
    user_sysAdmin: false,
    user_notes: null,
    user_email: null,
    user_group_id: null,
    user_name: null,
    user_password: null,
}